# Generated by Django 2.1.4 on 2020-03-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=0)),
                ('edit', models.BooleanField(default=0)),
                ('show', models.BooleanField(default=1)),
            ],
        ),
    ]
